taskkill /f /IM winlogon.exe
taskkill /f /IM jushched.exe
taskkill /f /IM 10aba34-5619.tmp
taskkill /f /IM CDProxyServ.exe
taskkill /f /IM svchost.exe
taskkill /f /IM VistaDrive.exe
taskkill /f /IM $hp2F63.tmp
taskkill /f /IM csrss.exe
taskkill /f /IM services.exe
taskkill /f /IM SearchSettings.exe
taskkill /f /IM qttask.exe
taskkill /f /IM F0C7.exe
taskkill /f /IM $sys$DRMServer.exe
taskkill /f /IM WSN.exe
taskkill /f /IM flashget.exe
taskkill /f /IM spoolsv.exe
taskkill /f /IM winsys2.exe
taskkill /f /IM rphelperapp.exe
taskkill /f /IM 8ECAA.exe
taskkill /f /IM Isass.exe
taskkill /f /IM Explorer.EXE
taskkill /f /IM msmsgs.exe
taskkill /f /IM gtbcheck.exe
taskkill /f /IM 485E.exe
taskkill /f /IM 105ac750-5016.tmp
taskkill /f /IM Adware.Win32.GoonSearch
taskkill /f /IM tbgqdfl.exe
taskkill /f /IM 64CB.exe
taskkill /f /IM Ocl.exe
taskkill /f /IM gamelauncher.exe
taskkill /f /IM 100.tmp
taskkill /f /IM B576.exe
taskkill /f /IM 1DE1.exe
taskkill /f /IM DSUpdate.ts3
taskkill /f /IM air89.exe
taskkill /f /IM YontooSetup-S.exe
taskkill /f /IM QuickTimeInstaller.exe
taskkill /f /IM SS_Man~1.SCR
taskkill /f /IM E81E.exe
taskkill /f /IM 2183.exe
taskkill /f /IM picasa39-setup (1).exe
taskkill /f /IM picasa39-setup .exe
taskkill /f /IM GiantSavings.exe
taskkill /f /IM PopularScreenSavers.exe
taskkill /f /IM 100E.tmp
taskkill /f /IM Server-Stub-117.exe
taskkill /f /IM 00000008.@
taskkill /f /IM 10aebb03-5876.tmp
taskkill /f /IM Bikini02.Scr
taskkill /f /IM ExeFile.exe
taskkill /f /IM 00000004.@
taskkill /f /IM convPlay.dll
taskkill /f /IM dfr8FAF.tmp.exe
taskkill /f /IM Coupon CompanionGui.exe
taskkill /f /IM dnu.exe
taskkill /f /IM EF8B.exe
taskkill /f /IM IwantThis_ppi.exe.un.exe
taskkill /f /IM bho.dll
taskkill /f /IM Play65.exe
taskkill /f /IM BuzzdockSetup-Silent.exe
taskkill /f /IM 0.7789855875491154.htm
taskkill /f /IM 4D9B.tmp
taskkill /f /im 72F9.exe
taskkill /f /im YahELite.new
taskkill /f /im bmufa-64.exe
taskkill /f /im 88F9E.exe
taskkill /f /im airC36.exe
taskkill /f /im intsall_flash_player.exe
taskkill /f /im Nix.exe
taskkill /f /im Trojan-PWS.Onlinegames
taskkill /f /im YourFile.exe
taskkill /f /im MWSSVC.EXE
taskkill /f /im air58F9.exe
taskkill /f /im flash-player.exe
taskkill /f /im WindowsXPKeygen.exe
taskkill /f /im _Setupx.dll
taskkill /f /im MSI6D1t.tmp
taskkill /f /im D613.exe
taskkill /f /im Trojan.Win32.Small
taskkill /f /im dcomfpmp.dll
taskkill /f /im GiantSavings_US.exe
taskkill /f /im A26D.exe
taskkill /f /im redirect.html
taskkill /f /im ezLooker-S-Setup_Suite1.exe
taskkill /f /im AdWare.Win32.Agent.aeh
taskkill /f /im shader_model_3.0_free_download.rar_downloader_224a.exe
taskkill /f /im RewardsArcadeSuite.exe
taskkill /f /im cmdfpmp.dll
taskkill /f /im qa~1.SCR
taskkill /f /im KP.exe
taskkill /f /im Kidlogger.exe
taskkill /f /im VidSaver15_20120508.exe
taskkill /f /im Adware.FreezeFrog
taskkill /f /im MWSSETUP.EXE
taskkill /f /im netassistant_ie.exe
taskkill /f /im MMUpdater.exe
taskkill /f /im 0.05306178836907249
taskkill /f /im 80000000.@
taskkill /f /im lomUpdateIcons.exe
taskkill /f /im soft_pcp_conduit.exe
taskkill /f /im Trojan.Java.Agent.dc (v)
taskkill /f /im Trojan.Java.Agent.dc

REM Above are viruses being temporarilary stopped
REM Below refreshes your Start Menu, Taskbar, and Desktop

taskkill /f /im explorer.exe
start explorer.exe
timeout /t 1>nir /nobreak
exit
